#Connect Gateway

require include/raspberrypi-common.inc

PRECONFIGURED_SYSTEM_CONNECTIONS ?= "eth0"

USERADD_UID_TABLES ?= "files/static-user-ids/niot-e-tpi51-en-re/passwd"
USERADD_GID_TABLES ?= "files/static-user-ids/niot-e-tpi51-en-re/group"
