# We have a conf and classes directory, add to BBPATH
BBPATH := "${BBPATH}:${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES := "${BBFILES} ${LAYERDIR}/recipes-*/*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hilscher-netfield-raspberrypi"
BBFILE_PATTERN_hilscher-netfield-raspberrypi := "^${LAYERDIR}/"
BBFILE_PRIORITY_hilscher-netfield-raspberrypi = "100"

LAYERSERIES_COMPAT_hilscher-netfield-raspberrypi = "dunfell"
LAYERDEPENDS_hilscher-netfield-raspberrypi = "hilscher-netfield"

KEYS_DIR := "${LAYERDIR}/keys"

BSP_DEPLOYSCRIPT_DIR = "${LAYERDIR}/scripts/deploy"
