#!/bin/sh

platform_init_enabled() {
	return 0
}

platform_init_run() {
	# load modules for devices
	load_kernel_module usbnet
	load_kernel_module smsc95xx

	__debug "Exporting the platform gpios ..."
	echo 24 >     /sys/class/gpio/export
	echo in >     /sys/class/gpio/gpio24/direction
	echo rising > /sys/class/gpio/gpio24/edge
	echo 1 >      /sys/class/gpio/gpio24/active_low

	__debug "Creating platform symlinks ..."

	# LEDs
	ln -s /sys/class/leds/led0/brightness /var/platform/update_led
	ln -s /sys/class/leds/user0:orange:user/brightness /var/platform/led_led2
	ln -s /sys/class/leds/user1:orange:user/brightness /var/platform/led_led1

	# Enable rtc to make sure systemd shows correct time stamps
	echo pcf8563 0x51 > /sys/class/i2c-adapter/i2c-1/new_device
	hwclock -s

	# Insert nvram
	echo 24c64 0x54 > /sys/class/i2c-adapter/i2c-1/new_device

#	echo "Initializing the LED startup behavior ..."
#	echo heartbeat > $(dirname $(readlink /var/platform/led_pg0))/trigger

	mmcdev="/dev/mmcblk0"
	if [ ! -b "${mmcdev}" ]; then
		# NOTE: The old device tree (used in netFIELD-OS 2.4) does not provide a firmware reference
		#       within the sdhost node. The latest kernel driver (netFIELD-OS 2.5) relies on this.
		#       During an usb system recovery process the newer kernel may run with an old device tree (of the previous
		#       system) which then leads to an compatibility conflict. As a result the driver will be deferred and the
		#       system block device is missing. The fix is done in two steps:
		#       1. the overlay provides the missing firmware reference
		#       2. the reset of the usb interface triggers deferred probing

		echo "Loading sdhost device tree overlay (firmware reference)..."
		mount -t configfs none /sys/kernel/config
		mkdir -p /sys/kernel/config/device-tree/overlays/mmc-firmware/
		cat /boot/dt-overlays/rpi-mmc-firmware-overlay.dtbo > /sys/kernel/config/device-tree/overlays/mmc-firmware/dtbo

		usbdev=$(blkid --label RECOVERY)
		if [ -n "${usbdev}" ]; then
			usbsyspath=$(udevadm info -q property --property="DEVPATH" $usbdev | cut -d "/" -f 2-8)
			usbsyspath=$(dirname /sys/${usbsyspath})"/authorized"
			echo 0 > ${usbsyspath}
			echo 1 > ${usbsyspath}

			echo "Waiting for usb recovery device ${usbdev}..."
			while [ ! -b "${usbdev}" ]; do
				sleep 1
			done
		fi

		echo "Waiting for system block device ${mmcdev}..."
		while [ ! -b "${mmcdev}" ]; do
			sleep 1
		done
	fi
}
